### ISSUE TITLE
License File and pkg.go.dev

### ISSUE THREAD

**Issue by nelsam** [bugst/go-json#1]
I am considering using bugst/go-lsp for my text editor, but pkg.go.dev doesn't understand the LICENSE file in this repo, so it won't load the docs. That's probably not the _worst_ thing in the world, but it does make pkg.go.dev/go.bug.st/lsp harder to read since clicking on `json.RawMessage` takes me to this: https://pkg.go.dev/go.bug.st/json#RawMessage

**Comment by cmaglie** [comment]
Let me try to copy the original license.

**Comment by nelsam** [comment]
AFAIK that will work, but you'll need to release a new version before `pkg.go.dev` will pick it up. Thanks!
